version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: irabu-dev-redis

    mariadb:
      image: mariadb:10.4
      container_name: irabu-dev-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=irabu
        - MYSQL_DATABASE=irabu
        - MYSQL_USER=irabu
        - MYSQL_PASSWORD=irabu
      ports:
        - "8003:3306"

    webserver:
      image: nginx:alpine
      container_name: irabu-dev-webserver
      working_dir: /application
      network_mode: bridge
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      depends_on: # start this container after the dependencies
       - php-fpm
      ports:
       - "80"
      environment: 
        VIRTUAL_HOST: irabu.co.tz, irabu.dev
        LETSENCRYPT_HOST: irabu.co.tz, irabu.dev
        LETSENCRYPT_EMAIL: info@irabu.co.tz

    php-fpm:
      build: phpdocker/php-fpm
      container_name: irabu-dev-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
networks:
  default:
    external:
      name: nginx-proxy
