version: "3.1"
services:

    php-fpm:
      build: phpdocker/php-fpm
      container_name: ira-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      environment:
        SERVICE_NAME: php-fpm

    redis:
      image: redis:alpine
      container_name: ira-redis

    mariadb:
      image: mariadb:10.4
      container_name: ira-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=irabu
        - MYSQL_DATABASE=irabu
        - MYSQL_USER=irabu
        - MYSQL_PASSWORD=irabu
      ports:
        - "8003:3306"

    app:
      image: nginx:alpine
      container_name: ira-app
      working_dir: /application
      network_mode: bridge
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      depends_on:
       - php-fpm
      ports:
       - "80"
      environment: 
        VIRTUAL_HOST: irabu.co.tz, irabu.dev
        LETSENCRYPT_HOST: irabu.co.tz, irabu.dev
        LETSENCRYPT_EMAIL: info@irabu.co.tz
    
networks:
  default:
    external:
      name: nginx-proxy
